Life parameteres
lkszjakubowski/tamagotchi pull request #4
Opened 2023-03-01 21:39 UTC by lkszjakubowski

2023-03-02 13:13 UTC, Sumick requested changes
Nice job - it works properly, but we need to focus on getting this code more maintainable.

- [x] Split this huge `decreaseStats` method into smaller, reusable pieces
- [x] Fix intervals, so they are accessible within whole class

2023-03-02 13:13 UTC, Sumick commented on js/game.js
> +  decreaseStats = ({
**nitpick:** This method is definitely too big. Let's split it in smaller, reusable and domain specific code pieces. Example: `decreaseHealth() {...}, decreaseEnergy() {...}` etc. You should be able to call such methods independently

2023-03-02 13:13 UTC, Sumick commented on js/game.js
> +    const interval = setInterval(() => {
**nitpick:** Your intervals are closed in this specific method scope. What if you'd like to stop specific interval by calling any action that is not a part of that `decreaseStats` method? You don't have any control right now. Try to mount such intervals in the constructor. Eg. `this.energyDecreaseInterval = setInterval(() => {...}, 1000)`. By doing that you can access such interval from any part of your class scope, giving you full control

2023-03-02 19:20 UTC, lkszjakubowski commented on js/game.js
> +  decreaseStats = ({
thanks for the tips! updated my code

2023-03-02 19:29 UTC, lkszjakubowski commented on js/game.js
> +  decreaseStats = ({
just noticed a weird behavior of the health paremater, interval skips values

2023-03-03 10:52 UTC, Sumick approved these changes
Amazing job! It looks great 👌 

PS. Next time, please re-send review request from Nerdbord task - without it don't have any notification that you are ready to review, thanks:)

2023-03-03 10:56 UTC, merged